services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: netrikan-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: mobile_app/Dockerfile.web
    container_name: netrikan-web
    depends_on:
      - backend
    ports:
      - "8080:80"
    restart: unless-stopped
