FROM ghcr.io/cirruslabs/flutter:stable AS build

WORKDIR /app
COPY mobile_app /app
RUN flutter pub get
RUN flutter build web --release --dart-define=API_BASE_URL=http://localhost:8000

FROM nginx:1.27-alpine
COPY docker/nginx-web.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build/web /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
